{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-generic.fullname" . }}
  labels:
    {{- include "microservice-generic.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
